inputs:
  version:
    description: "A version to install ecspresso"
    default: latest
    required: false
runs:
  using: "composite"
  steps:
    - shell: bash
      working-directory: /tmp
      run: |
        set -e
        echo "::warning ecspresso@v1 is deprecated. Please use ecspresso@v2 action."
        VERSION="${{ inputs.version }}"
        if [ "${VERSION}" = "latest" ]; then
          $VERSION=v1.7.15
          echo "::notice Using fixed latest v1 version: ${VERSION}"
        fi
        DOWNLOAD_URL=https://github.com/kayac/ecspresso/releases/download/${VERSION}/ecspresso_${VERSION:1}_linux_amd64.tar.gz
        cd /tmp
        curl -sfLO ${DOWNLOAD_URL}
        if [[ "${DOWNLOAD_URL}" =~ \.tar\.gz$ ]]; then
          FILENAME=$(basename $DOWNLOAD_URL .tar.gz)
          tar xzvf ${FILENAME}.tar.gz
          sudo install ecspresso /usr/local/bin/ecspresso
        elif [[ "${DOWNLOAD_URL}" =~ \.zip$ ]]; then
          FILENAME=$(basename $DOWNLOAD_URL .zip)
          unzip ${FILENAME}.zip
          sudo install ${FILENAME} /usr/local/bin/ecspresso
        fi
